### ISSUE TITLE
No posts of account owner and posts of users that are followed by the account owner on "Home" screen

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#412]
Preconditions:
- Test user is signed in;
- Test user following users with posts;
- Test user has posts;

Steps to reproduce:
1. Open side panel
2. Tap on "Home" item in the panel

Actual Result: No posts on "Home" screen
Expected Result: Posts of account owner and posts of users that are followed by the account owner are displayed on "Home" screen

**Comment by orezhko** [comment]
Verified on Android - it doesn't have owner posts

**Comment by sharadagarwal** [comment]
I have two clarifications on expected behavior:
- A user cannot follow herself. Her own topics should not appear on her following topics feed (i.e. GET /v0.7/users/me/following/topics )
- When a user follows some other user, then new topics that the other user creates should appear in her following topics feed
I hope this is the behavior you are experiencing. If not, please re-open this issue.
